import os

ARTICLE_TITLE_MIN_LENGTH = 8
ARTICLE_TITLE_MAX_LENGTH = 128
ARTICLE_CONTENT_MAX_LENGTH = 32768
ARTICLE_CONTENT_MIN_LENGTH = 512

TUTORIAL_TITLE_MIN_LENGTH = 8
TUTORIAL_TITLE_MAX_LENGTH = 128