version: '3.0'
services:
  api-server:
    image: codehub-backend
    container_name: 'api_server'
    depends_on:
      - postgres
    expose:
      - '8000'
    env_file:
      - ./config/backend.env
  postgres:
    image: codehub-postgres
    container_name: 'postgresql'
    expose:
      - '5432'
    env_file:
      - ./config/db.env
  angular:
    image: codehub-frontend
    container_name: 'angular'
    expose:
      - '4200'
  nginx:
    image: codehub-nginx
    container_name: 'nginx_main'
    ports:
      - '80:80'
    links:
      - api-server
      - angular