version: '3.0'
services:
  api-server:
    image: code-hub.org:5000/codehub-backend
    container_name: 'api_server'
    restart: always
    depends_on:
      - postgres
    expose:
      - '8000'
    env_file:
      - ./config/backend.env
  postgres:
    image: code-hub.org:5000/codehub-postgres
    container_name: 'postgresql'
    restart: always
    expose:
      - '5432'
    env_file:
      - ./config/db.env
  angular:
    image: code-hub.org:5000/codehub-frontend
    container_name: 'angular'
    restart: always
    expose:
      - '4200'
    env_file:
      - ./config/angular.env
  nginx:
    image: code-hub.org:5000/codehub-nginx
    container_name: 'nginx_main'
    restart: always
    ports:
      - '80:80'
    links:
      - api-server
      - angular
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - '6379:6379'
