version: '3.0'
services:
  web:
    image: codehub-backend
    depends_on:
      - postgres
    expose:
      - '8000'
    env_file:
      - ./config/backend.env
  postgres:
    image: codehub-postgres
    expose:
      - '5432'
    env_file:
      - ./config/db.env
  nginx:
    image: codehub-nginx
    ports:
      - '80:80'
    links:
      - web
