# Generated by Django 2.2.8 on 2020-04-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('preview', models.TextField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('published', models.BooleanField(default=False)),
                ('text', models.TextField(db_index=True, default='article content', max_length=32768)),
                ('estimate_reading_time', models.IntegerField(default=1)),
                ('preview', models.TextField()),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_articles',
                                   to=settings.AUTH_USER_MODEL)),
                ('next_article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      related_name='prev_article', to='articles.Article')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                                               to='tutorials.Tutorial')),
            ],
        ),
    ]
