# Generated by Django 2.2.8 on 2020-04-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('preview', models.TextField(blank=True, max_length=1024, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('published', models.BooleanField(default=False)),
                ('text', models.TextField(db_index=True, default='article content', max_length=32768)),
                ('estimate_reading_time', models.IntegerField(default=1)),
                ('preview', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_articles',
                                   to=settings.AUTH_USER_MODEL)),
                ('tutorial',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                                   to='tutorials.Tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('edited', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                              to='tutorials.TutorialArticle')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='tutorial_articles_comments', to=settings.AUTH_USER_MODEL)),
                ('reply_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies',
                                   to='tutorials.TutorialArticleComment')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticleReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                              to='tutorials.TutorialArticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticleCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=8)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                              to='tutorials.TutorialArticleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tutorialarticlereaction',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='user_tutorial_article'),
        ),
        migrations.AddConstraint(
            model_name='tutorialarticlecommentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='user_tutorial_article_comment'),
        ),
    ]
