# Generated by Django 2.2.8 on 2020-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialarticle',
            name='next_article',
        ),
    ]
