# Generated by Django 2.2.8 on 2020-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200510_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialarticle',
            name='text',
            field=models.TextField(default='article content'),
        ),
    ]
