# Generated by Django 2.2.8 on 2020-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tutorials', '0002_remove_tutorialarticle_next_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='preview',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
