# Generated by Django 2.2.8 on 2020-04-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200412_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialarticle',
            name='tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tutorials.Tutorial'),
        ),
    ]
