# Generated by Django 2.2.8 on 2020-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tutorials', '0004_auto_20200413_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialarticle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
