# Generated by Django 2.2.8 on 2020-04-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0006_auto_20200415_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('edited', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                              to='tutorials.TutorialArticle')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='tutorial_articles_comments', to=settings.AUTH_USER_MODEL)),
                ('reply_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies',
                                   to='tutorials.TutorialArticleComment')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialArticleCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=8)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                              to='tutorials.TutorialArticleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
