# Generated by Django 2.2.8 on 2020-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tutorials', '0007_tutorialarticlecomment_tutorialarticlecommentreaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tutorialarticlecommentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='user_comment'),
        ),
    ]
