# Generated by Django 2.2.8 on 2020-01-24 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('published', models.BooleanField(default=False)),
                ('text', models.TextField(db_index=True, default='article content', max_length=32768)),
                ('estimate_reading_time', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
