# Generated by Django 2.2.8 on 2020-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0003_article_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
