# Generated by Django 2.2.8 on 2020-04-20 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_auto_20200419_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='likes',
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=8)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                                 to='articles.ArticleComment')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='user_comment'),
        ),
    ]
