# Generated by Django 2.2.8 on 2020-04-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0007_auto_20200420_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                    to='articles.ArticleComment'),
        ),
    ]
