# Generated by Django 2.2.6 on 2019-12-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehubuser',
            name='view_permission_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codehubuser',
            name='view_permission_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodehubUserLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='codehubuserlinks',
            constraint=models.UniqueConstraint(fields=('link', 'user'), name='Link-User constraint'),
        ),
    ]
