# Generated by Django 2.2.8 on 2020-04-21 08:40

from django.db import migrations, models

import content.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', content.models.CodehubFileField(blank=True, max_length=200, null=True, upload_to='media')),
            ],
        ),
    ]
