# Generated by Django 2.2.8 on 2020-04-28 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='view_permission_all',
        ),
        migrations.RemoveField(
            model_name='user',
            name='view_permission_registered',
        ),
    ]
