# Generated by Django 2.2.8 on 2020-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20200428_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('request_id', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
