# Generated by Django 2.2.8 on 2020-05-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_notifications(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserNotifications = apps.get_model('accounts', 'UserNotifications')
    for user in User.objects.all():
        UserNotifications.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_changepasswordrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_comment', models.BooleanField(default=True)),
                ('comment_reply', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_notifications, reverse_code=migrations.RunPython.noop)
    ]
