# Generated by Django 2.2.8 on 2020-06-29 12:11

from django.db import migrations

import content.models


def set_default_avatar(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.avatar = 'media/default-avatar.png'
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=content.models.CodehubFileField(blank=True, max_length=200, null=True, upload_to='media'),
        ),
        migrations.RunPython(set_default_avatar, reverse_code=migrations.RunPython.noop)
    ]
