# Generated by Django 2.2.8 on 2021-01-30 13:48

from django.db import migrations

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CodehubUserManager()),
            ],
        ),
    ]
